# GitHub Pages 配置
title: Python交互式编程教程
description: 基于JupyterLite和ThebeLab的交互式Python学习平台
url: "https://zihao0106.github.io"
baseurl: "/my-python-course"

# 构建设置
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 包含和排除文件
include:
  - lite
  - assets
  - chapters

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github