# GitHub Pages 配置
title: Python交互式编程教程
description: 基于JupyterLite和Bootstrap的交互式Python学习平台
url: ""  # 将在GitHub Pages部署时自动设置
baseurl: ""  # 将在GitHub Pages部署时自动设置

# 构建设置
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 包含和排除文件
include:
  - lite
  - assets
  - chapters

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github